version: 2

builds:
  - main: ./cmd/harvest-tui
    binary: harvest-tui
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
